# Generated by Django 5.2.11 on 2026-02-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('income', models.FloatField()),
                ('loan_amount', models.FloatField()),
                ('credit_score', models.IntegerField()),
                ('employment_years', models.IntegerField()),
                ('existing_debt', models.FloatField()),
                ('risk_probability', models.FloatField(blank=True, null=True)),
                ('loan_status', models.CharField(blank=True, max_length=20, null=True)),
                ('decision_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
